<PongBall>:
    size: 50, 50
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<PongPaddle>:
    size: 25, 200
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<PongGame>:
    ball: pong_ball
    player1: player_left
    player2: player_right

    canvas:
        Color:
            rgba: 1, 1, 1, 0.2
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height

    Label:
        font_size: 70
        center_x: self.parent.width / 4
        top: self.parent.top - 50
        text: str(self.parent.player1.score)

    Label:
        font_size: 70
        center_x: self.parent.width * 3 / 4
        top: self.parent.top - 50
        text: str(self.parent.player2.score)

    PongBall:
        id: pong_ball
        center: self.parent.center

    PongPaddle:
        id: player_left
        x: self.parent.x
        center_y: self.parent.center_y

    PongPaddle:
        id: player_right
        x: self.parent.width - self.width
        center_y: self.parent.center_y
